# Generated by Django 3.1.7 on 2021-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210305_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='script',
            field=models.TextField(max_length=1000),
        ),
    ]
